CREATE DATABASE [Crud]
GO
ALTER DATABASE [Crud] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Crud] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Crud] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Crud] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Crud] SET ARITHABORT OFF 
GO
ALTER DATABASE [Crud] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Crud] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Crud] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Crud] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Crud] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Crud] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Crud] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Crud] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Crud] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Crud] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Crud] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Crud] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Crud] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Crud] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Crud] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Crud] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Crud] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Crud] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Crud] SET  MULTI_USER 
GO
ALTER DATABASE [Crud] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Crud] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Crud] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Crud] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Crud] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Crud]
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[data](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[email] [varchar](50) NOT NULL,
	[birth_date] [datetime] NOT NULL,
 CONSTRAINT [PK_data] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Crud] SET  READ_WRITE 
GO